# Rotation matrices have determinant 1

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

In [2]:
a = 30
cosa = np.cos(np.deg2rad(a))
sina = np.sin(np.deg2rad(a))
R = np.array([[cosa,-sina],[sina,cosa]])

In [5]:
np.linalg.det(R)

1.0

### Rotation matrices inverse is their transpose

In [9]:
np.linalg.inv(R)

array([[ 0.8660254,  0.5      ],
       [-0.5      ,  0.8660254]])

In [11]:
R.T

array([[ 0.8660254,  0.5      ],
       [-0.5      ,  0.8660254]])

# if you swap any row or colum of the rotation matrix, it stays orthogonal but its determinant changes and so the matrix becomes a reflection

In [15]:
Rf = R[[1,0],:] # take first row ad all colums
np.linalg.det(Rf)

-1.0

In [17]:
Rf.T

array([[ 0.5      ,  0.8660254],
       [ 0.8660254, -0.5      ]])

In [19]:
np.linalg.inv(Rf)

array([[ 0.5      ,  0.8660254],
       [ 0.8660254, -0.5      ]])

# converting a transformation matrix into affine form

In [22]:
A = np.array([[Rf[0,0],Rf[0,1],0],[Rf[1,0],Rf[1,1],0],[0,0,1]])
A

array([[ 0.5      ,  0.8660254,  0.       ],
       [ 0.8660254, -0.5      ,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])