## Structuring element/kernel slides over the image and can take different shapes built in opencv and can fit the shape in 3 different ways

In [4]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [5]:
K_r = cv2.getStructuringElement(cv2.MORPH_RECT,(5,5)) # rectangular kernel with 5 x 5 dimensions

In [6]:
type(K_r)

numpy.ndarray

In [7]:
K_r.dtype

dtype('uint8')

In [12]:
K_r

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [22]:
K_e = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(10,10)) # ellipse

In [24]:
K_e

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0]], dtype=uint8)

In [26]:
K_c = cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5)) # cross

In [28]:
K_c

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)